development:
  adapter: postgresql
  database: ftm_development
  host: localhost
test:
  adapter: postgresql
  database: ftm_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: ftm_production
  pool: 5
  timeout: 5000